### ISSUE TITLE
Constantly getting NoSuchField error on new setup

### ISSUE THREAD

**Issue by vseguin** [vkononov/fillable-pdf#44]
Hi @vkononov,

I've been trying to add fillable-pdf to a new project, both locally and in Heroku.
I am using version 0.9.6 (latest) version here, but have the same problem with earlier versions. Note that between versions, the NoSuchFieldError error message changes (and stack trace as well) but still.

Getting the following error while opening any PDF file:
```
rake aborted!
NoSuchFieldError: LEFT
/Users/vincentseguin/.rvm/gems/ruby-3.3.0/gems/fillable-pdf-0.9.6/lib/fillable-pdf/itext.rb:14:in `import'
/Users/vincentseguin/.rvm/gems/ruby-3.3.0/gems/fillable-pdf-0.9.6/lib/fillable-pdf/itext.rb:14:in `block in <module:ITEXT>'
/Users/vincentseguin/.rvm/gems/ruby-3.3.0/gems/fillable-pdf-0.9.6/lib/fillable-pdf/suppress_warnings.rb:6:in `suppress_warnings'
/Users/vincentseguin/.rvm/gems/ruby-3.3.0/gems/fillable-pdf-0.9.6/lib/fillable-pdf/itext.rb:10:in `<module:ITEXT>'
/Users/vincentseguin/.rvm/gems/ruby-3.3.0/gems/fillable-pdf-0.9.6/lib/fillable-pdf/itext.rb:7:in `<class:FillablePDF>'
/Users/vincentseguin/.rvm/gems/ruby-3.3.0/gems/fillable-pdf-0.9.6/lib/fillable-pdf/itext.rb:6:in `<top (required)>'
/Users/vincentseguin/.rvm/gems/ruby-3.3.0/gems/fillable-pdf-0.9.6/lib/fillable-pdf.rb:1:in `require_relative'
/Users/vincentseguin/.rvm/gems/ruby-3.3.0/gems/fillable-pdf-0.9.6/lib/fillable-pdf.rb:1:in `<top (required)>'
/Users/vincentseguin/Desktop/dev/deployment/lib/tasks/continuation_page.rake:3:in `<top (required)>'
/Users/vincentseguin/.rvm/gems/ruby-3.3.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/Users/vincentseguin/.rvm/gems/ruby-3.3.0/bin/ruby_executable_hooks:22:in `eval'
/Users/vincentseguin/.rvm/gems/ruby-3.3.0/bin/ruby_executable_hooks:22:in `<main>'
(See full trace by running task with --trace)
```

My code is (assume myfile is a pdf file here)
```
pdf = FillablePDF.new 'myfile.pdf'
```

My Java version is
```
bash-3.2$ java -version
openjdk version "11.0.22" 2024-01-16
OpenJDK Runtime Environment Homebrew (build 11.0.22+0)
OpenJDK 64-Bit Server VM Homebrew (build 11.0.22+0, mixed mode)
```

Using Ruby 3.3.0 as a Ruby version.

I've tried the same on a brand new Rails app, and also in Heroku - always getting the same error.

Any guidance would be great!

**Comment by tfader** [comment]
Same behaviour regardless to ruby version (3.2.3, 3.3.0, etc).

**Comment by tfader** [comment]
works with rjb v1.6

**Comment by vseguin** [comment]
@tfader confirmed it works on my side. Thanks! Created https://github.com/vkononov/fillable-pdf/pull/45.
