### ISSUE TITLE
Constant DL and Fiddile is not defined

### ISSUE THREAD

**Issue by kobiyoyo** [vkononov/fillable-pdf#7]
this is what i get whenever i run rails server

load the gem 'fillable-pdf'. (Bundler::GemRequireError)
Gem Load Error is: Constants DL and Fiddle is not defined.
Backtrace for gem load error is:
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/fillable-pdf-0.7.1/lib/fillable-pdf/itext.rb:3:in `load'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/fillable-pdf-0.7.1/lib/fillable-pdf/itext.rb:3:in `<main>'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `block in require'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `require'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `require_relative'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/fillable-pdf-0.7.1/lib/fillable-pdf.rb:1:in `<main>'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/runtime.rb:76:in `each'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/runtime.rb:76:in `block in require'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/runtime.rb:65:in `each'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/runtime.rb:65:in `require'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler.rb:114:in `require'
/home/chubiyojo/Desktop/Rails Apps/Dissect/config/application.rb:20:in `<main>'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `block in require'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `require'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/railties-6.0.1/lib/rails/commands/server/server_command.rb:141:in `block in perform'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/railties-6.0.1/lib/rails/commands/server/server_command.rb:138:in `tap'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/railties-6.0.1/lib/rails/commands/server/server_command.rb:138:in `perform'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/railties-6.0.1/lib/rails/command/base.rb:65:in `perform'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/railties-6.0.1/lib/rails/command.rb:46:in `invoke'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/railties-6.0.1/lib/rails/commands.rb:18:in `<main>'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `block in require'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/chubiyojo/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `require'
bin/rails:4:in `<main>'
Bundler Error Backtrace:

**Comment by vkononov** [comment]
@kobiyoyo Are you able to provide more information about this issue? I am unable to reproduce it.
